In [ ]:
# Data Source - https://drive.google.com/drive/folders/10SUoVOHnv95fLr-w2HSktjQUd96jXA3U?usp=sharing
# Dataset - https://drive.google.com/file/d/1HqTcjEjTTb9-4o6RezlY3BHwHFeQdbn9/view?usp=sharing

In [ ]:
# import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# sklearn libraries
from sklearn.preprocessing import OneHotEncoder

# ignore harmless warnings
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# data import
data = pd.read_csv('/content/drive/MyDrive/Datasets/Input/Housing.csv')

# data sample
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [ ]:
# dimension of the data
data.shape

(545, 13)

In [ ]:
# basic data quality check
pd.DataFrame({'missing_values': data.isnull().sum(),
              'datatype': data.dtypes})

                  missing_values datatype
price                          0    int64
area                           0    int64
bedrooms                       0    int64
bathrooms                      0    int64
stories                        0    int64
mainroad                       0   object
guestroom                      0   object
basement                       0   object
hotwaterheating                0   object
airconditioning                0   object
parking                        0    int64
prefarea                       0   object
furnishingstatus               0   object

# ONE HOT ENCODING

In [ ]:
# list of all categorical columns

# list comprehension
cat_cols = [cols for cols in data.columns if data[cols].dtype == 'O']

# classes in each of the columns
for cols in cat_cols:
    print(cols, ':', data[cols].unique())

mainroad : ['yes' 'no']
guestroom : ['no' 'yes']
basement : ['no' 'yes']
hotwaterheating : ['no' 'yes']
airconditioning : ['yes' 'no']
prefarea : ['yes' 'no']
furnishingstatus : ['furnished' 'semi-furnished' 'unfurnished']

In [ ]:
# one hot encoding using sklearn
sk_encoder = OneHotEncoder(sparse_output=False, drop='first', dtype='i2')
out_arr = sk_encoder.fit_transform(data[cat_cols])
sk_encoded_df = pd.DataFrame(out_arr, columns=sk_encoder.get_feature_names_out())

# lets concat the numerical column with encoded columns
sk_encoded_df = pd.concat([data.drop(cat_cols, axis=1), sk_encoded_df], axis=1)
sk_encoded_df.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0

In [ ]:
# Pandas - get_dummies
get_dummies = pd.get_dummies(data, drop_first=True, dtype='i2')
get_dummies.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0

# HOME WORK #

# use penguin data

    # do one hot encoding on penguin data using both methods
    # see how the missing values are handled differently in these two methods

In [ ]:
# loading the penguin data
pdata = sns.load_dataset('penguins')

# data sample
pdata.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [ ]:
# data volume
pdata.shape

(344, 7)

In [ ]:
# data with missing values
pdata[pdata.isnull().any(axis=1)]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN
246,Gentoo,Biscoe,44.5,14.3,216.0,4100.0,NaN
286,Gentoo,Biscoe,46.2,14.4,214.0,4650.0,NaN
324,Gentoo,Biscoe,47.3,13.8,216.0,4725.0,NaN
336,Gentoo,Biscoe,44.5,15.7,217.0,4875.0,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN

In [ ]:
# conver the data to one hot representation
encoded_pdata = pd.get_dummies(pdata, drop_first=True, dtype='i2')
encoded_pdata

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,species_Chinstrap,species_Gentoo,island_Dream,island_Torgersen,sex_Male
0,39.1,18.7,181.0,3750.0,0,0,0,1,1
1,39.5,17.4,186.0,3800.0,0,0,0,1,0
2,40.3,18.0,195.0,3250.0,0,0,0,1,0
3,NaN,NaN,NaN,NaN,0,0,0,1,0
4,36.7,19.3,193.0,3450.0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...
339,NaN,NaN,NaN,NaN,0,1,0,0,0
340,46.8,14.3,215.0,4850.0,0,1,0,0,0
341,50.4,15.7,222.0,5750.0,0,1,0,0,1
342,45.2,14.8,212.0,5200.0,0,1,0,0,0
343,49.9,16.1,213.0,5400.0,0,1,0,0,1

In [ ]:
# lets filer the encoded data with raw data index where there are missing values

encoded_pdata.iloc[pdata[pdata.isnull().any(axis=1)].index]

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,species_Chinstrap,species_Gentoo,island_Dream,island_Torgersen,sex_Male
3,NaN,NaN,NaN,NaN,0,0,0,1,0
8,34.1,18.1,193.0,3475.0,0,0,0,1,0
9,42.0,20.2,190.0,4250.0,0,0,0,1,0
10,37.8,17.1,186.0,3300.0,0,0,0,1,0
11,37.8,17.3,180.0,3700.0,0,0,0,1,0
47,37.5,18.9,179.0,2975.0,0,0,1,0,0
246,44.5,14.3,216.0,4100.0,0,1,0,0,0
286,46.2,14.4,214.0,4650.0,0,1,0,0,0
324,47.3,13.8,216.0,4725.0,0,1,0,0,0
336,44.5,15.7,217.0,4875.0,0,1,0,0,0
339,NaN,NaN,NaN,NaN,0,1,0,0,0

In [ ]:
ndata = sns.load_dataset('taxis')
ndata.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
pd.DataFrame({'Missingvalue': ndata.isnull().sum(),
              'datatype': ndata.dtypes})

                 Missingvalue        datatype
pickup                      0  datetime64[ns]
dropoff                     0  datetime64[ns]
passengers                  0           int64
distance                    0         float64
fare                        0         float64
tip                         0         float64
tolls                       0         float64
total                       0         float64
color                       0          object
payment                    44          object
pickup_zone                26          object
dropoff_zone               45          object
pickup_borough             26          object
dropoff_borough            45          object

In [ ]:
# filtering only the cat cols
nc_data = ndata.select_dtypes(exclude=['int', 'float', 'datetime'])

# data sample for cat cols
nc_data.head()

,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
# data volume
nc_data.shape

(6433, 6)

In [ ]:
# missing values
nc_data[nc_data.isnull().any(axis=1)]

,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
7,yellow,NaN,Murray Hill,Flatiron,Manhattan,Manhattan
42,yellow,credit card,NaN,NaN,NaN,NaN
445,yellow,NaN,Boerum Hill,Columbia Street,Brooklyn,Brooklyn
491,yellow,NaN,Murray Hill,Murray Hill,Manhattan,Manhattan
545,yellow,NaN,LaGuardia Airport,Forest Hills,Queens,Queens
...,...,...,...,...,...,...
6118,green,credit card,Prospect Heights,NaN,Brooklyn,NaN
6169,green,NaN,Jackson Heights,Jackson Heights,Queens,Queens
6311,green,NaN,Long Island City/Hunters Point,Long Island City/Hunters Point,Queens,Queens
6314,green,cash,Jamaica,NaN,Queens,NaN
6356,green,cash,Stuyvesant Heights,NaN,Brooklyn,NaN

In [ ]:
# dummies
ncd_data = pd.get_dummies(nc_data, drop_first=True, dtype='i2')

# data sample
nc_data.head()

,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
# lets filer the encoded data with raw data index where there are missing values

ncd_data.iloc[nc_data[nc_data.isnull().any(axis=1)].index]

,color_yellow,payment_credit card,pickup_zone_Alphabet City,pickup_zone_Astoria,pickup_zone_Auburndale,pickup_zone_Battery Park,pickup_zone_Battery Park City,pickup_zone_Bay Ridge,pickup_zone_Bayside,pickup_zone_Bedford,...,dropoff_zone_World Trade Center,dropoff_zone_Yorkville East,dropoff_zone_Yorkville West,pickup_borough_Brooklyn,pickup_borough_Manhattan,pickup_borough_Queens,dropoff_borough_Brooklyn,dropoff_borough_Manhattan,dropoff_borough_Queens,dropoff_borough_Staten Island
7,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
42,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
445,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
491,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
545,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6118,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
6169,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
6311,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
6314,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
6356,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [ ]:
nc_data[nc_data['pickup_zone'].isnull() == True]

,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
42,yellow,credit card,NaN,NaN,NaN,NaN
606,yellow,credit card,NaN,Upper East Side South,NaN,Manhattan
622,yellow,credit card,NaN,NaN,NaN,NaN
671,yellow,cash,NaN,Lincoln Square East,NaN,Manhattan
712,yellow,credit card,NaN,West Chelsea/Hudson Yards,NaN,Manhattan
970,yellow,credit card,NaN,NaN,NaN,NaN
1108,yellow,credit card,NaN,NaN,NaN,NaN
1961,yellow,credit card,NaN,Garment District,NaN,Manhattan
2137,yellow,credit card,NaN,NaN,NaN,NaN
2742,yellow,credit card,NaN,NaN,NaN,NaN
3085,yellow,cash,NaN,NaN,NaN,NaN
3259,yellow,credit card,NaN,NaN,NaN,NaN
3644,yellow,credit card,NaN,NaN,NaN,NaN
3793,yellow,NaN,NaN,Midtown East,NaN,Manhattan
3889,yellow,cash,NaN,NaN,NaN,NaN
4118,yellow,credit card,NaN,NaN,NaN,NaN
4127,yellow,cash,NaN,NaN,NaN,NaN
4281,yellow,credit card,NaN,NaN,NaN,NaN
4414,yellow,credit card,NaN,NaN,NaN,NaN
4772,yellow,credit card,NaN,NaN,NaN,NaN
4941,yellow,credit card,NaN,NaN,NaN,NaN
5263,yellow,credit card,NaN,NaN,NaN,NaN
5493,green,credit card,NaN,NaN,NaN,NaN
5624,green,cash,NaN,NaN,NaN,NaN
5638,green,credit card,NaN,NaN,NaN,NaN
6083,green,credit card,NaN,NaN,NaN,NaN

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
export = ncd_data.iloc[nc_data[nc_data['pickup_zone'].isnull() == True].index]

In [ ]:
export.to_csv('/content/sample_data/test_data.csv')